project_id = "blyuzmnuhuymcptqinqa"

[functions.enhance-skin]
verify_jwt = false

[functions.generate-character-image]
verify_jwt = false

[functions.extract-image-prompt]
verify_jwt = false

[functions.extract-dress-to-dummy]
verify_jwt = false

[functions.remove-people-from-image]
verify_jwt = false

[functions.generate-music]
verify_jwt = false

[functions.pose-transfer]
verify_jwt = false

[functions.apply-makeup]
verify_jwt = false

[functions.full-look-transfer]
verify_jwt = false
