project_id = "blyuzmnuhuymcptqinqa"

[functions.enhance-skin]
verify_jwt = false

[functions.generate-character-image]
verify_jwt = false

[functions.extract-image-prompt]
verify_jwt = false

[functions.extract-dress-to-dummy]
verify_jwt = false